### PR TITLE
Update rj45_keystone_receiver.scad

### PR DESCRIPTION
**Pull request by jdodgen**
I found my jacks were hard to insert so I took apart the code to see how to make it easier to insert.  Now things can be adjusted. If you set clip_adjustment = 0, you produce the original.

### CODE REVIEW

**Comment by jdodgen** [comment]
BTW what generated the original?

**Comment by marcuswu** [comment]
> BTW what generated the original?

The original was written by hand ages ago in openscad from a lot of measurements on a keystone I had when I first got into 3D printing.

This looks really good. I added a comment asking for removal of some commented code, but after that I'm ready to merge it.

**Comment by jdodgen** [comment]
I removed the commented  code and cleaned stuff up.  All that written by hand, I am impressed.

**Comment by jdodgen** [comment]
Here is what I built with it.  (https://github.com/jdodgen/keystone-patch-panel)

**Comment by jdodgen** [comment]
Good enough for a merge? Not sure how everthing works yet.  I retired 14 years ago, still coding but have not used Git much.

**Comment by marcuswu** [comment]
Yes, I wanted to run it locally since I don't have any github actions on this repo just to have a quick verification. Sorry it took a little  bit to get to.

**Pull request merged**
